<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'AclPlugin\Module'                            => __DIR__ . '/Module.php',
  'AclPlugin\Controller\Plugin\AclPluginPlugin' => __DIR__ . '/src/AclPlugin/Controller/Plugin/AclPluginPlugin.php',
  'AclPlugin\Service\AclPermissionConfig'       => __DIR__ . '/src/AclPlugin/Service/AclPermissionConfig.php',
);
